# Generated by Django 3.2.5 on 2022-05-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="ActionFile", new_name="Action",),
    ]
