# Generated by Django 3.2.5 on 2022-05-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_group_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="studing_form",
            field=models.CharField(
                choices=[("О", "Очно"), ("З", "Заочно")],
                default="st",
                max_length=2,
                verbose_name="форма обучения",
            ),
        ),
    ]
