# Generated by Django 3.2.5 on 2022-05-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_group_studing_form'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='githubuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='actions_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.action', verbose_name='файл с настройками проверки (.yaml)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.subject', verbose_name='задание'),
        ),
    ]
