name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
         mypy-options: "--ignore-missing-imports --show-error-codes"
         isort-options: "-w 100"
         django: true

