name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Python Linter
      uses: sunnysid3up/python-linter@v0.1-beta.7

